name: Mule Action
description: Action to test and deploy Mule Apps

inputs:
  testParams:
    description: Parameters for Maven test goal (must include all -D directives)
    required: true
  deployParams:
    description: Parameters for Maven deploy goal (must include all -D directives)
    required: true
  muleUsername:
    description: Username for deploying
    required: true
  mulePassword:
    description: Password for deploying
    required: true
  nexusUsername:
    description: Username for Nexus repository
    required: true
  nexusPassword:
    description: Password for Nexus repository
    required: true
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    
    - name: Configure setting.xml with Anypoint Platform credentials
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        output_file: .m2/settings.xml
        repositories: >
          [
            {
              "id": "MuleRepository",
              "name": "MuleRepository",
              "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "true"
              }
            }
          ]
        servers: >
          [
            {
              "id": "anypoint-exchange-v2",
              "username": "${{ inputs.muleUsername }}",
              "password": "${{ inputs.mulePassword }}"
            },
            {
              "id": "mulesoft-releases",
              "username": "${{ inputs.muleUsername }}",
              "password": "${{ inputs.mulePassword }}"
            },
            {
              "id": "MuleRepository",
              "username": "${{ inputs.nexusUsername }}",
              "password": "${{ inputs.nexusPassword }}"
            },
            {
              "id": "Repository",
              "username": "${{ inputs.muleUsername }}",
              "password": "${{ inputs.mulePassword }}"
            }
          ]
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: PRINT STUFF
      run: echo ${{ inputs.muleUsername }} ${{ inputs.mulePassword }}
      shell: bash
        
    # test, package y deploy a exchange
    
    - name: Test with Maven. Assumes coverage values configured in pom.xml
      run: mvn clean test -X ${{ inputs.testParams }}
      shell: bash
      
    - name: Package with Maven skipping tests
      run: mvn clean package -DskipTests
      shell: bash

    - name: Deploy with Maven
      run: mvn clean deploy -DskipTests -DmuleDeploy ${{ inputs.deployParams }}
      shell: bash

