name: Mule Action
description: Action to test and deploy Mule Apps

inputs:
  mvnParams:
    description: Variables passed to Maven with -D flag
    required: true
  MULE_USERNAME:
    description: Username for deploying
    required: true
  MULE_PASSWORD:
    description: Password for deploying
    required: true
  MULE_REPO_USERNAME:
    description: Username for Nexus repository
    required: true
  MULE_REPO_PASSWORD:
    description: Password for Nexus repository
    required: true
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    
    - name: Configure setting.xml with Anypoint Platform credentials
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        output_file: .m2/settings.xml
        repositories: >
          [
            {
              "id": "MuleRepository",
              "name": "MuleRepository",
              "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "true"
              }
            }
          ]
        servers: >
          [
            {
              "id": "anypoint-exchange-v2",
              "username": "${{inputs.MULE_USERNAME}}",
              "password": "${{inputs.MULE_PASSWORD}}"
            },
            {
              "id": "mulesoft-releases",
              "username": "${{inputs.MULE_USERNAME}}",
              "password": "${{inputs.MULE_PASSWORD}}"
            },
            {
              "id": "MuleRepository",
              "username": "${{inputs.MULE_REPO_USERNAME}}",
              "password": "${{inputs.MULE_REPO_PASSWORD}}"
            },
            {
              "id": "Repository",
              "username": "${{inputs.MULE_USERNAME}}",
              "password": "${{inputs.MULE_PASSWORD}}"
            }
          ]
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    # test, package y deploy a exchange

    #- name: Deploy with Maven
    #  run: mvn clean deploy ${{ inputs.mvnParams }}
    #  shell: bash
    - name: Download file
      uses: DownloadSecureFile@1
      displayName: 'Download settings-mule.xml'
      inputs:
        secureFile: 'settings-mule.xml'
